baseURL = "https://kcjug.github.io/"
languageCode = "en"
[markup.goldmark.renderer]
unsafe = true

# Exclude footer section from generating list pages (index.html and index.xml)
[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]
  footer = []

# Explicitly prevent the footer section from generating any output
[outputFormats.footerSection]
# Empty configuration to prevent any output

# Specifically disable generation of these kinds for the footer content
disableKinds = ["footerSection", "RSS"]

[module]
[[module.imports]]
path = "github.com/zetxek/adritian-free-hugo-theme"

## Base mounts - so your site's assets are available
[[module.mounts]]
source = "archetypes"
target = "archetypes"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "i18n"
target = "i18n"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "static"
target = "static"

# The following mounts are required for the theme to be able to load bootstrap
# Remember also to copy the theme's `package.json` to your site, and run `npm install`
[[module.mounts]]
source = "node_modules/bootstrap/scss"
target = "assets/scss/bootstrap"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js"
target = "assets/js/bootstrap"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
target = "assets/js/vendor/bootstrap.bundle.min.js"

[[module.mounts]]
source = "node_modules/bootstrap-print-css/css/bootstrap-print.css"
target = "assets/css/bootstrap-print.css"

[params]
title = 'KCJUG'
description = 'Kansas City Java User Group'
images = ['/img/og-img.png']
sections = [
]
# If you want to display an image logo in the header, you can add it here
# logo = '/img/hugo.svg'

homepageExperienceCount = 6

[params.analytics]
## Analytics parameters.
### Supported so far: Vercel (Page Insights, Analytics)
### And Google (Tag Manager, Analytics)
# controls vercel page insights - disabled by default
# to enable, just set to true
vercelPageInsights = false
vercelAnalytics = false

# google analytics and tag manager. to enable, set "enabled" to true
# and add the tracking code (UA-something for analytics, GTM-something for tag manager)
[params.analytics.googleAnalytics]
enabled = false
[params.analytics.googleTagManager]
enabled = false

[build]
writeStats = true

[build.buildStats]
enabledFor = ["scss"]
disableClasses = false
disableIDs = false
disableTags = false
enable = true

[params.languages.selector.disable]
footer = true
header = true
mobileHeader = false

[languages]
[languages.en]
disabled = false
languageCode = 'en'
languageDirection = 'ltr'
languageName = 'English'
weight = 0

[languages.en.menus]
[[languages.en.menus.header]]
#pre = "meetup"
name = "Meetup"
URL = "https://www.meetup.com/KansasCityJUG/"
weight = 1

[[languages.en.menus.header]]
#pre = "meetup"
name = "Slack"
URL = "http://kansascityjug.slack.com/"
weight = 1

# Plugins
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "css/custom.css"
[[params.plugins.css]]
URL = "css/adritian-icons.css"
## Print css
[[params.plugins.css]]
URL = "css/bootstrap-print.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"

# SCSS Plugins
[[params.plugins.scss]]
URL = "scss/adritian.scss"

# theme/color style 
[params.colorTheme]
  [params.colorTheme.auto]
     disable = true
  [params.colorTheme.forced]
    theme = "light"

[params.colorTheme.selector.disable]
footer = true
header = true
mobileHeader = true

[params.blog]
layout = "sidebar-right"     # options: default (no sidebar), sidebar, sidebar-right
sidebarWidth = "25"    # percentage width of the sidebar
showCategories = true
showRecentPosts = true
recentPostCount = 5
listStyle = "summary"  # options: simple, summary
featured_sort_by_weight = true
featured_sort_by_date = false

[params.experience]
showJobCard = true # Set to false to hide the job card
